### ISSUE TITLE
Add two new functions

### ISSUE THREAD

**Issue by whlsxl** [power-assert-js/power-assert#116] opened 2018-12-27 03:06 UTC
From node v10.0.0, `node assert` add two new function,  [assert.doesNotReject](https://nodejs.org/api/assert.html#assert_assert_doesnotreject_asyncfn_error_message) and [assert.rejects](https://nodejs.org/api/assert.html#assert_assert_rejects_asyncfn_error_message)
Can we add this two function in `power-assert` ?

**Comment by azu** [comment] 2018-12-27 03:15
Duplicate of #107 
We will support these in [power-assert v2](https://github.com/power-assert-js/power-assert/labels/power-assert-v2).

**Closed by azu** 2018-12-27 03:15 UTC
